# ---------- Frontend build ----------
FROM node:22-alpine AS frontend

WORKDIR /app

COPY web/dashboard/package.json web/dashboard/package-lock.json ./web/dashboard/

RUN cd web/dashboard && \
    npm ci --no-audit --no-fund --ignore-scripts

COPY web/dashboard ./web/dashboard

RUN cd web/dashboard && npm run build


# ---------- Go build ----------
FROM --platform=$BUILDPLATFORM golang:1.27.1-alpine3.24 AS builder

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Dashboard generated by Vite
COPY --from=frontend \
    /app/internal/admin/dashboard/static/dist \
    /app/internal/admin/dashboard/static/dist

ARG VERSION=dev
ARG COMMIT=none
ARG DATE=unknown

RUN CGO_ENABLED=0 \
    GOOS=${TARGETOS} \
    GOARCH=${TARGETARCH} \
    GOARM=${TARGETVARIANT#v} \
    go build \
    -ldflags="-s -w \
    -X github.com/enterpilot/gomodel/internal/version.Version=${VERSION} \
    -X github.com/enterpilot/gomodel/internal/version.Commit=${COMMIT} \
    -X github.com/enterpilot/gomodel/internal/version.Date=${DATE}" \
    -o /gomodel ./cmd/gomodel

RUN mkdir -p /app/.cache /app/data && \
    touch /app/.cache/.keep /app/data/.keep


# ---------- Runtime ----------
FROM gcr.io/distroless/static-debian12:nonroot

LABEL io.modelcontextprotocol.server.name="io.github.ENTERPILOT/gomodel"

COPY --from=builder /gomodel /gomodel
COPY --from=builder /app/config/*.yaml /app/config/

COPY --from=builder --chown=65532:65532 /app/.cache /app/.cache
COPY --from=builder --chown=65532:65532 /app/data /app/data

WORKDIR /app

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD ["/gomodel", "--health"]

ENTRYPOINT ["/gomodel"]
